### ISSUE TITLE
Unable to get SuggestView from ymaps

### ISSUE THREAD

**Issue by Shams0045** [ddubrava/angular8-yandex-maps#101]
# ❓ Help Wanted

Please give me a hint, where is my mistake?

Using [this](https://stackblitz.com/edit/suggest-view-vhx6js?file=src%2Fapp%2Fapp.component.ts) sample and using new service (YaApiLoaderService), getting error TS2339: Property 'SuggestView' does not exist on type 'typeof ymaps'.

Here is the code: 

ngOnInit(): void {
this.yaApiLoaderService.load().subscribe(ymaps => {
       const suggest = new ymaps.SuggestView('suggest');
       suggest.events.add(['select'], e => console.log(e));
      console.log(ymaps);
    });
  }

console.log(ymaps); -> shows SuggestView as well.

"angular8-yandex-maps": "^12.1.4",
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cli                    11.2.13
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.1.5

**Comment by ddubrava** [comment]
Hi, in such cases please use type casting `new (ymaps as any).SuggestView('suggest');`. Exported type definitions may not have some properties. I'll add `SuggestView` in `ymaps` in the next release.

**Comment by Shams0045** [comment]
Thank you very much, it works!
