### ISSUE TITLE
Broken depedencies

### ISSUE THREAD

**Issue by kirill85** [ddubrava/angular8-yandex-maps#110]
# 🐞 Bug Report
Couldn't install library on current angular version
## ✍️ Description
Couldn't install library on Angular 12.1.0

## 🔬 Reproduction

1. Setup new minimal Angular progect.
2. Run npm i angular8-yandex-maps in project directory

## 🌎 Environment

Angular  12.1.3

angular8-yandex-maps 
[2021-07-25T05_49_52_698Z-debug.log](https://github.com/ddubrava/angular8-yandex-maps/files/6873445/2021-07-25T05_49_52_698Z-debug.log)
[eresolve-report.txt](https://github.com/ddubrava/angular8-yandex-maps/files/6873448/eresolve-report.txt)
12.1.5

**Comment by ddubrava** [comment]
Hi, thanks for submitting your bug.
Fixed in `"angular8-yandex-maps": "12.1.6"`
