### ISSUE TITLE
The namespace ymaps was declared in non-npm package.

### ISSUE THREAD

**Issue by SnowRisesToTheSky** [ddubrava/angular8-yandex-maps#124]
Добрый день. Я некоторое время искал причину, по которой у меня не видно пространства имен ymaps при использовании angular8-yandex-maps. Я делал по примеру: https://stackblitz.com/edit/placemark?file=node_modules%2Fangular8-yandex-maps%2Flib%2Ftypings%2Fyandex-maps%2Findex.d.ts. И когда, при поиске решения, догадался в этом примере отыскать где-же определено это пространство имен, то обнаружил, что оно находится в index.d.ts. Я в angular новичок. Но как мне кажется, его не видно в моем проекте из-за того что оно было объявлено в .d.ts. И там-же, в этом же файле как-раз в оглавлении и написано: "Type definitions for non-npm package yandex-maps 2.1."

**Comment by SnowRisesToTheSky** [comment]
Я решил проблему, заменив это:
interface PlacemarkConstructor {
  geometry: number[];
  properties: ymaps.IPlacemarkProperties;
  options: ymaps.IPlacemarkOptions;
}

на это:
export interface IPlacemarkConstructor {
  geometry: number[];
  properties: { balloonContent:string };
  options: { preset:string };
}

**Comment by ddubrava** [comment]
Привет, какая версия библиотеки? Чтобы тайпинги работали, ничего не надо делать, кроме установки библиотеки.
