### ISSUE TITLE
Sending api request on application start 

### ISSUE THREAD

**Issue by Shams0045** [ddubrava/angular8-yandex-maps#125]
# ❓ Help Wanted

## ✍️  Sending api request to https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey="" on application start.
            I'm not calling maps on application start. 
           So, how can I prevent api request if yandex maps is not called?
 

## 🌎 Angular

@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cdk                    12.2.5
@angular/cli                    11.2.13
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.1.5

"angular8-yandex-maps": "^12.1.4"

**Comment by ddubrava** [comment]
Hi! Sorry, I don't get it. API loads when you use a `ya-map` component. If you don't need an API on application start, you can hide the map using the directive. BTW, you can check [YaApiLoaderService](https://ddubrava.github.io/angular8-yandex-maps/injectables/YaApiLoaderService.html) if you want to get rid of a component

**Comment by Shams0045** [comment]
While loading home page there is a request to API, but the yandex maps component is hidden. I'm not calling component in home page. 
My configuration is Own map config
import { AngularYandexMapsModule, YaConfig } from 'angular8-yandex-maps';

const mapConfig: YaConfig = {
  apikey: 'API_KEY',
  lang: 'en_US',
};

@NgModule({
  imports: [AngularYandexMapsModule.forRoot(mapConfig)],
})
export class AppModule {}

**Comment by Shams0045** [comment]
Yes, you were right, sorry for interrupting you. My mistake was for using custom modal to call maps component. That custom modal was loading in application start.
