### ISSUE TITLE
Add default yandex CSP to readme.md

### ISSUE THREAD

**Issue by rempash** [ddubrava/angular8-yandex-maps#170]
Hi
We usually work with angular in the enterprise environment, and most of the time we need CSP to make requests and get resources for external libraries. Maybe I can add an example of CSP for yandex-maps, because some URLs cannot be found in their documentation, so users of this library can just copy the CSP string and add it to their project.

**Comment by ddubrava** [comment]
Hi! You can create a repro on stackblitz, I'll fork it and send you a link, then you can raise a PR.
Or any other ideas?
