### ISSUE TITLE
Low performance with a large number of markers when using ngFor

### ISSUE THREAD

**Issue by hardcorelite** [ddubrava/angular8-yandex-maps#194]
# 🐞 Bug Report

## ✍️ Description

Low performance with a large number of markers when using ngFor

## 🔬 Reproduction

```
<ya-map (ready)="onReady($event)" id="map" [center]="[helper.lat, helper.lng]" [zoom]="8" [state]="{ controls: [] }">
     <ya-clusterer>
         <ng-container *ngFor="let row of users">
               <ya-placemark *ngIf="row.lat" [geometry]="[row.lat, row.lng]" [options]="getOptionsBaloon(row)" (yaclick)="viewDriver(row)"></ya-placemark>
         </ng-container>
      </ya-clusterer>
</ya-map>
```

**Comment by ddubrava** [comment]
hey, thanks for you issue. it would be great if you could provide a reproduction since it can't reproduce this.

**Comment by ddubrava** [comment]
Reproduction - https://stackblitz.com/edit/creating-a-clusterer-hrtcwv?file=src/app/app.component.ts

**Comment by ddubrava** [comment]
\>= 16, a `ready` event runs outside of an Angular Zone;
< 16, if you face with performance issues, do not use `ya-placemark` and use `ymaps.Placemark` instead.
