### ISSUE TITLE
angular 14 problem with search

### ISSUE THREAD

**Issue by Emperor577** [ddubrava/angular8-yandex-maps#195]
when I am going to search some place with SearchControl  or using geocode, it returns the error 403. And when I look at the payload there isn't apiKey value in it. So how can I fix this?

<img width="615" alt="Screenshot 2023-04-13 at 18 31 19" src="https://user-images.githubusercontent.com/42857664/231774531-3ef3c5e0-3d04-4382-8841-7ae98c8040f7.png">

<img width="1266" alt="Screenshot 2023-04-13 at 18 32 05" src="https://user-images.githubusercontent.com/42857664/231774732-e25b32fe-cb7e-4fd5-8e1a-cd571b0ed996.png">

<img width="471" alt="Screenshot 2023-04-13 at 18 32 18" src="https://user-images.githubusercontent.com/42857664/231774820-bf10d9bc-4963-4cfd-98bd-a95a52171e76.png">

<img width="569" alt="Screenshot 2023-04-13 at 18 34 06" src="https://user-images.githubusercontent.com/42857664/231775774-534c7d88-3df1-45d6-a59d-3a0bd1ed7ddb.png">

**Comment by ddubrava** [comment]
Hi! Could you provide a reproduction, please? It seems that you provide a configuration not in an app.module.
It works here - https://stackblitz.com/edit/direct-geocoding-flhvue?file=src/app/app.module.ts

**Comment by Emperor577** [comment]
yes you are right i set configuration in submodule AppModule -> SaleModule -> PosModuel here inside pos module provide configurations. Sales and pos modules are lazy loaded module

**Comment by Emperor577** [comment]
well, that's worked. I added it to the shared module and it works. Thanks a lot

**Comment by ddubrava** [comment]
Great. You should provide a configuration in an AppModule, and then just import `AngularYandexMapsModule` in lazy modules.
