### ISSUE TITLE
как получить значения адреса from и to c routePanel?❓ - 

### ISSUE THREAD

**Issue by iromfire** [ddubrava/angular8-yandex-maps#200]
### Description

пытался достать с помощью routePanel.state.get('from') но дает координаты, а не адрес

**Comment by ddubrava** [comment]
Привет!

Пример с получением всех адресов с использованием библиотеки - https://stackblitz.com/edit/get-reference-points-via-route-panel?file=src/app/app.component.ts

Пример из документации Яндекс.Карт, где из активного маршрута получают данные. activeRoute не содержит адреса, но основная идея такая же - https://yandex.ru/dev/maps/jsapi/doc/2.1/dg/concepts/router/routePanel.html#routePanel__get-route-info

**Comment by iromfire** [comment]
я использую данный пример https://stackblitz.com/edit/calculating-delivery-cost?file=src%2Fapp%2Fapp.component.ts. как в данном случае получить адреса? буду очень благодарен

**Comment by ddubrava** [comment]
Этот пример идентичен вышеуказанному, необходимо внутрь условия на 49 строке вставить получение `wayPoints`.

```
if (activeRoute) {
  const wayPoints = route.model.getWayPoints();
  const addresses = wayPoints.map((point) => point.properties.get('address'));
  ...
}
```

**Comment by iromfire** [comment]
спасибо!
