### ISSUE TITLE
🐞 - peerDependencies should be added with a caret (^)

### ISSUE THREAD

**Issue by omqmo** [ddubrava/angular8-yandex-maps#201]
### Description

Поскольку версия `angular` выше чем версия используемая в данной библиотеке, то в новом проекте при попытке установить какую-либо зависимость через `npm` возникает потребность в флаге `-f`. Это сводит на нет очарование от данного стека. Поэтому, я просто решил напомнить, что при поддержке библиотек для `angular` необходимо синхронизироваться с выходом новой версии. Иначе, жизнь превращается в кошмар. Спасибо.

**Comment by ddubrava** [comment]
Привет, огромное спасибо за репорт! Криво смигрировали с Angular CLI на Nx и потеряли версии в package.json

**Comment by omqmo** [comment]
@ddubrava огромное спасибище за столь быстрое решение! Лично меня дико напрягает подобный момент.
