### ISSUE TITLE
🐞 - IMultiRouteParams.routingMode is missing 'bicycle'

### ISSUE THREAD

**Issue by PLUG13** [ddubrava/angular8-yandex-maps#204]
### Description

According to ymaps [documentation](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/IMultiRouteParams.html) IMultiRouteParams routingMode can be set to "bicycle". Please, add "bicycle" mode support.

**Comment by PLUG13** [comment]
Btw it works perfectly out of the box with some typings hacks so its just typings problem

**Comment by ddubrava** [comment]
Hi, thanks for your report. Update to `16.0.2`
