### ISSUE TITLE
❓ - Конфликт между YandexMap и SwiperJS

### ISSUE THREAD

**Issue by Rouvas** [ddubrava/angular8-yandex-maps#208]
### Description

Приветствую! На текущий момент не могу понять, с чьей стороны ошибка. 

На момент, пока скрипт Яндекс карт не подгружен (с помощью данной библиотеки), все ок. Как только он подгружается, Swiper, при взаимодействии с ним начинает ругаться на эвенты (при этом работает корректно, как и Яндекс.Карты (при взаимодействии с ними, так же, ошибок нет)). 

Что удивительно, но если обратиться к ошибке, то отправляет к "Я.Картам". 

<img width="542" alt="image" src="https://github.com/ddubrava/angular8-yandex-maps/assets/15251194/027816b6-c7f3-458d-9e9d-9e249d1b1065">

Предполагаю, что, возможно проблема не с картами и библиотекой обвязкой, но возможно все. Заранее спасибо за ответ!

🌎 Dependencies
    "@angular/animations": "^14.2.0",
    "@angular/cdk": "^14.2.7",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",
    "angular8-yandex-maps": "^14.0.3",
    "rxjs": "~7.5.0",
    "swiper": "^9.4.1",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

**Comment by ddubrava** [comment]
Привет, сделай, пожалуйста, **минимальный** пример на Stackblitz, потому что просто по коду непонятно. Ошибки летят из свайпера, надо смотреть откуда точно и смотреть дебагер. Я накидал маленький пример, где обе библиотеки используются - проблем не было

**Comment by Rouvas** [comment]
Большое спасибо, что помогаете разобраться. Ссылка на [Stackblitz](https://stackblitz.com/edit/angular-ivy-uaxxaa?file=src%2Fapp%2Fdirectives%2Fswiper.directive.ts), [демо](https://angular-ivy-uaxxaa.stackblitz.io)

**Comment by ddubrava** [comment]
Я попробовал убрать весь ангуляр, библиотеку с картами и использовать API карт напрямую + кастомные элементы - та же проблема. Видимо, карты модицифируют событие, если такое возможно. 

Попробуй оставить в свайпере ишью с вопросом возможно ли, что сторонняя библиотека удаляет `event.touches`, вот воспроизведение  - https://stackblitz.com/edit/swiper-yandex-maps-bug. Заодно можно закинуть вопрос в Яндекс.Карты, но они долго будут отвечать, скорее всего.

Я, к сожалению, не могу дебажить долго, за вечер ничего не выяснил. Баг странный, но он не про либу, а про карты. Еще важно отметить, что если использовать свйапер + карты вне ангуляр, то все ок. То есть возможно еще проблема в зонах.

**Comment by Rouvas** [comment]
Понял, спасибо за разбор! Буду пробовать писать им. Пока не закрываю ветку, если будет решение, опубликую, для кого-нибудь будет полезным

**Comment by Rouvas** [comment]
upd. На Angular 17 с использованием Swiper 11 и angular8-yandex-maps 17.1.0 ошибок не наблюдается
