### ISSUE TITLE
🐞 - FeatureRemovedError

### ISSUE THREAD

**Issue by Musin-Mihail** [ddubrava/angular8-yandex-maps#225]
### Description

Во время поиска в консоли возникает ошибка FeatureRemovedError. При этом поиск проходит нормально.
![Screenshot_1493](https://github.com/ddubrava/angular8-yandex-maps/assets/39467173/192c0fc4-17c9-42dd-8f7f-e6db5d94c079)
![Screenshot_1494](https://github.com/ddubrava/angular8-yandex-maps/assets/39467173/3e8a348b-b5b7-40b3-bec7-9a153307ad53)
![Screenshot_1495](https://github.com/ddubrava/angular8-yandex-maps/assets/39467173/1040aecc-be62-47e6-aaa4-1234ead78fcf)

### Angular version

16.2.12

### Library version

17.0.1

**Comment by ddubrava** [comment]
Привет, я не могу помочь без кода. Ошибка из API Яндекс.Карт, поэтому проблема, скорее всего, не в библиотеке. Из гугла есть такой комментарий по поводу ошибки - https://modx.pro/components/9382#comment-141125. Предлагают прокинуть `suggest_apikey`, его нет в документации к параметрам скрипта, но есть тут - https://yandex.com/dev/jsapi-v2-1/doc/en/v2-1/ref/reference/suggest.

Попробуй, пожалуйста, его прокинуть. Если это поможет, то я добавлю его в интерфейс.

```
export const mapConfig$ = new BehaviorSubject<YaConfig & { suggest_apikey: string }>({
  apikey: environment.apikey,
  suggest_apikey: '',
});

@NgModule({
  declarations: [AppComponent],
  imports: [AngularYandexMapsModule.forRoot(mapConfig$), BrowserModule],
  bootstrap: [AppComponent],
})
export class AppModule {}
```
