### ISSUE TITLE
🚀 - Support Yandex.Maps API v3

### ISSUE THREAD

**Issue by ddubrava** [ddubrava/angular8-yandex-maps#226]
### Description

Yandex.Maps API v3 is released. We need to support both versions.

### Notes

- There are official typings, check them - https://yandex.ru/dev/jsapi30/doc/ru/dg/concepts/typescript

**Comment by Rouvas** [comment]
Подскажите, когда ожидать поддержку v3? :)

**Comment by ddubrava** [comment]
Не могу сказать пока что, там не быстро и не получится прикрутить к этому же пакету

**Comment by ddubrava** [comment]
`angular-yandex-maps-v3` is released. Currently, there are not many classes, I'm working on this
