### ISSUE TITLE
❓ - icon image and icon title

### ISSUE THREAD

**Issue by mstgnz** [ddubrava/angular8-yandex-maps#231]
### Description

hello, first of all thanks for the package.

i need examples about icon image and icon content(title). can you help me.

```ts
public placemarkOptions: ymaps.IPlacemarkOptions = {}

// this is working.
this.placemarkOptions.iconColor = "red"

// this is not working
this.placemarkOptions.iconImageHref = "assets/img/incident.png"
```
```html
<ya-map [center]="center" [options]="mapOptions">
    <ya-placemark [geometry]="center" [options]="placemarkOptions" (yadragend)="draggend($event)"></ya-placemark>
</ya-map>
```

I also want to use title and image for each icon in `multiroute`.

```html
<ya-multiroute  [referencePoints]="markers"></ya-multiroute>
```

Can you share examples for these?

**Comment by ddubrava** [comment]
Hi!

To use the local image check this:
- https://stackblitz.com/edit/custom-placemark?file=src%2Fapp%2Fapp.component.ts

To customize a multiroute check this:
- https://yandex.com/dev/maps/jsbox/2.1/multiroute_view_options/ - example
- https://yandex.com/dev/jsapi-v2-1/doc/en/v2-1/ref/reference/multiRouter.MultiRoute#param-options - options

**Comment by ddubrava** [comment]
> Thank you very much.

If you have any questions, feel free to ping me

**Comment by ddubrava** [comment]
You should define them in properties, not options. Check this - https://yandex.com/dev/jsapi-v2-1/doc/en/v2-1/ref/reference/Placemark#param-properties. The library is just a wrapper, it takes your inputs and pass them to the API.

**Comment by mstgnz** [comment]
Thanks a lot, but how do we do the same in `multiRoute` objects. there is no `multiRoute` properties parameter.

I couldn't find an example of `iconContent` for `multiRoute` here

https://yandex.com/dev/jsapi-v2-1/doc/en/v2-1/ref/reference/multiRouter.MultiRoute#param-options

The code below is the running code.

```html
<div class="container" style="width: 100%; height: 500px;">
  <ya-map [center]="center" [options]="mapOptions" [state]="{ controls: [] }">
      <ya-multiroute 
        [referencePoints]="markers"
        [options]="multirouteOptions"
      ></ya-multiroute>
  </ya-map>
</div>
```

```ts
public multirouteOptions: any = {}
ngOnInit(): void { 
    this.multirouteOptions = {
      wayPointStartIconLayout: "default#imageWithContent",
      wayPointStartIconImageHref: "assets/img/incident.png",
      wayPointStartIconImageSize: [30, 30],
      wayPointStartIconImageOffset: [-15, -15],
      wayPointFinishIconLayout: "default#imageWithContent",
      wayPointFinishIconImageHref: "assets/img/officeiconu.png",
      wayPointFinishIconImageSize: [30, 30],
      wayPointFinishIconImageOffset: [-15, -15]
    }
  }
```

**Comment by ddubrava** [comment]
In this [example](https://yandex.com/dev/maps/jsbox/2.1/multiroute_view_options/) in `customizeSecondPoint` they access `multiRoute.getWayPoints().get(1)` and set `iconContentLayout` using `yandexWayPoint.options.set`. You can try to do the same thing.

To access `multiRoute` you need to use `(ready)` on your `ya-multiroute` to get the instance.

```html
<ya-multiroute 
  [referencePoints]="markers"
  [options]="multirouteOptions"
  (ready)="onReady($event)"
></ya-multiroute>
```

```ts
onReady({ target }) {
  // do magic with the target, it's the instance
}
```

**Comment by ddubrava** [comment]
You can also pass a `geometry.Point` to reference points ([see this](https://yandex.com/dev/jsapi-v2-1/doc/en/v2-1/ref/reference/IMultiRouteReferencePoint)). To create a `[geometry.Point`](https://yandex.com/dev/jsapi-v2-1/doc/en/v2-1/ref/reference/geometry.Point) you can use `ymaps` from a map `ready` event. And then you can create a point with your own options. Instead of modifying them in a multiroute.

**Comment by mstgnz** [comment]
```html
<div class="container" style="width: 100%; height: 500px;">
  <ya-map [center]="center" [options]="mapOptions" [state]="{ controls: [] }">
      <ya-multiroute 
        [referencePoints]="markers"
        [options]="multirouteOptions"
        (ready)="onReady($event)"
      ></ya-multiroute>
  </ya-map>
</div>
```

```ts
onReady({ target }) {
    const yandexWayPoint = target.getWayPoints().get(1)
    yandexWayPoint.options.set({
        iconContentLayout: ymaps.templateLayoutFactory.createClass(
          '<span style="color: red;">TEST</span>andex'
        )
    })
}
```

result: undefined, i thing because 
<img width="621" alt="Screenshot 2024-01-31 at 18 40 13" src="https://github.com/ddubrava/angular8-yandex-maps/assets/9930661/fd548e95-ee4b-48a3-9c0f-b6e561a21bd8">

**Comment by mstgnz** [comment]
I got stuck in Angular typescript rules but that's okay, thank you for the solution and for taking the time to reply.
