### ISSUE TITLE
❓ - Problems with SuggestView

### ISSUE THREAD

**Issue by Lenetta** [ddubrava/angular8-yandex-maps#232]
### Description

Hello, dear developer!
I have a problem(
I need to use SuggestView, but I get the same error as in your example - it also doesn't work.

![image](https://github.com/ddubrava/angular8-yandex-maps/assets/33329240/e12e8a28-2f4f-4bb5-b4f1-b14b51452320)
![image](https://github.com/ddubrava/angular8-yandex-maps/assets/33329240/24cec920-d835-4ebd-9be3-1e69707dbd93)
I have a SuggestApiKey, but there is no field in the config where I can add it.
It’s in the documentation, but in fact it’s not.
![image](https://github.com/ddubrava/angular8-yandex-maps/assets/33329240/f0fdfcb7-278e-4357-b37e-1c701f2c0378)

I'm using version 13.2.0 for Angular 12.2.16.
Help me, please!

**Comment by Lenetta** [comment]
I solved this through inheritance and it works. But it would be nice to see information about this in the documentation.

![image](https://github.com/ddubrava/angular8-yandex-maps/assets/33329240/e61ad9a6-0fa1-440f-88c8-2657530320af)

**Comment by Lenetta** [comment]
Thank you very much!

**Comment by ddubrava** [comment]
`v15`, `v14` and `v13` are released. I added the missing property.

![image](https://github.com/ddubrava/angular8-yandex-maps/assets/22116465/90dcfcc1-ad78-4e69-ad5b-a4b113129e3d)
