### ISSUE TITLE
Использование сервиса напрямую

### ISSUE THREAD

**Issue by fr1mqa** [ddubrava/angular8-yandex-maps#30]
Добрый день.

Описание:
Можно ли использовать script.service напрямую, что бы использовать все возможности yandex API?

Или получить ymaps я могу только так https://stackblitz.com/edit/map-onload-event ?

**Comment by ddubrava** [comment]
Добрый день, ymaps только через onload event получается. Но теоретически могу сделать эскпорт сервиса, если это необходимо

**Comment by fr1mqa** [comment]
Это было бы просто прекрасно. Сейчас приходится создавать компонент с флагом onlyInstance, для доступу к геокодеру. Кстати, возможно стоит отключить обязательное задание координат в этом случае?
`<ya-map [onlyInstance]="true" [center]="[]" (load)="initYmapsObject($event)"></ya-map>`

**Comment by ddubrava** [comment]
Экспортировал [ScriptService](https://ddubrava.github.io/angular8-yandex-maps/#/services/script) в версии [8.1.0](https://www.npmjs.com/package/angular8-yandex-maps/v/8.1.0).

**Comment by fr1mqa** [comment]
Спасибо
