### ISSUE TITLE
Ошибка при использовании ya-clusterer

### ISSUE THREAD

**Issue by MaruBlare** [ddubrava/angular8-yandex-maps#32]
Добрый день!

Пытаюсь через ngFor вывести ya-placemark внутри ya-clusterer. При первой инциализации все хорошо отрабатывает. Вызываю роут на другой раздел приложения (в том же модуле), компонент, внутри которого карта, уничтожается без проблем, карта - тоже. Возвращаюсь к разделу с картой - при инициализации почему-то сразу вызывается ngOnDestroy у всех YaPlacemarkComponent, и при дестрое компонента-контейнера вылазит ошибка "Cannot read property 'geoObjects' of undefined", возникает она в методе ngOnDestroy YaPlacemarkComponent, т.к. там происходит обращение к _map.geoObjects, а свойство _map в этот момент является undefined.

Возможно я как-то неверно использую ya-clusterer?
![image](https://user-images.githubusercontent.com/29026396/95472011-3210d480-098b-11eb-900c-1bc8ad8794a3.png)

**Comment by MaruBlare** [comment]
P.S. Без кластера такой проблемы нет.

**Comment by ddubrava** [comment]
Добрый день, какая версия либы?

**Comment by MaruBlare** [comment]
Версия ^10.1.0.

Смотрите, кейс такой - placemarks я передаю как @Input() в компонент с картой. Данные по объектам в компоненте-контейнере я получаю асинхронно, поэтому изначально получается так, что вместо placemarks я отдаю null (пробовала также пустой массив, результат одинаковый), потому что данных пока нет, но когда они приходят, то, соответсвенно, обновляются данные для компонента карты. В примере это можно промоделировать, нажав Update Placemarks. Повторный вызов, а также роут в другой компонент вызовет ошибку  "Cannot read property 'geoObjects' of undefined".
Убрав компонент кластера эта ошибка перестает возникать. Я думаю что-то надо делать в ngOnChanges, как-то неправильно, наверное, обновляются точки на карте, но я не могу понять что именно надо сделать. 
https://stackblitz.com/edit/ya-clusterer-with-router-vw1cyo

**Comment by ddubrava** [comment]
Обновитесь до `10.2.0`, пожалуйста. Решилась проблема?

**Comment by MaruBlare** [comment]
Ошибка больше не воспроизводится.
Cпасибо!

**Comment by tonghae** [comment]
Добрый день! У меня тоже не обновляется состояние карты, но кейс немного другой. Без разницы есть ли кластеризация или нет. Ошибки в консоль не сыпятся, но визуальное обновление списка отметок происходит только когда я нажимаю что-либо на клавиатуре.

**Comment by ddubrava** [comment]
@tonghae, добрый день, попробуйте detectChanges вызывать при изменении.
Пример: [create-geoobject-onclick](https://stackblitz.com/edit/create-geoobject-onclick)
