### ISSUE TITLE
Placemark перемещается при скроле в Chrome\Edge и карта прогружается только когда скролишь в Mozilla

### ISSUE THREAD

**Issue by Denis-Evseev** [ddubrava/angular8-yandex-maps#33]
**Describe the bug**
1) Placemark перемещается при скроле в Chrome\Edge 
2) Карта прогружается только когда скролишь в Mozilla

Код простой 
```
                  <ya-map (load)="onMapLoad($event)" [center]="[]" [zoom]="16">
                    </ya-map>
```

```
  public async onMapLoad(event): Promise<any> {
    const res = await event.ymaps.geocode(this.vuz.Adress);

    // Выбираем первый результат геокодирования.
    const firstGeoObject = res.geoObjects.get(0);
    const coords = firstGeoObject.geometry.getCoordinates();

    // Масштабируем карту на область видимости геообъекта.
    event.instance.setCenter(coords);
    var placemark = new event.ymaps.Placemark(coords, {}, {
      balloonHeader: this.vuz.Name,
      balloonBody: '<img class="page_avatar_img" src="<url>' + this.vuz.Logo + '" alt="' + this.vuz.Name + '" width="100" height="100">',
      //balloonFooter: '<a href="../about" routerLinkActive="active"> Данные указаны не точно? </a>',
      draggable: false  
    });
    event.instance.geoObjects.add(placemark);
  }
```

**To Reproduce**
1. Используйте загрузку карты с меткой + масштабирование как у меня
2. Открыть браузеры указанные выше

**Expected behavior**
Думаю тут комментарии лишние 

**Screenshots**
![map](https://user-images.githubusercontent.com/9351603/95794983-1f770200-0ce1-11eb-802e-8b508ce33826.gif)

**Package version**
10.0.0

**Comment by ddubrava** [comment]
Привет! Если в твоем примере избавиться от `this.vuz`, заменить все на константы, то все будет работать. Возможно проблема, что `this.vuz` мутирует. В консоли есть какие-то ошибки от API? Потому что похоже, что в APIпопало что-то не то и оно сломалось.

Я немного подправил твой пример, сейчас рабочий - [geocoder-v2](https://stackblitz.com/edit/geocoder-v2?file=src/app/app.component.ts).

Посмотри еще, пожалуйста, на [placemark API](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/Placemark.html/#Placemark__param-properties), в твоем коде откуда-то `balloonHeader`, `balloonBody`, таких свойств не существует + они передаются вторым аргументом

**Comment by Denis-Evseev** [comment]
Спасибо за оперативный ответ, Даниил.

Вот живой пример:  https://vuzopoisk.ru/vuz/LRVJJInU/contacts.
Вижу только вот эту ошибку: 

net::ERR_ABORTED 400 (Bad Request)
GET https://api-maps.yandex.ru/services/coverage/v2/?l=map&ll=NaN,NaN&z=16&lang=ru_RU&callback=jsonp_yandex_coverage__l_map_ll_NaN_NaN_z_16_lang_ru_RU net::ERR_ABORTED 400 (Bad Request)

Не знаю относиться ли это к проблеме (такая же ошибка в Яндекс браузере и там все работает)

Спасибо за советы - обязательно посмотрю
