### ISSUE TITLE
Не обновляется состояние карты

### ISSUE THREAD

**Issue by ddubrava** [ddubrava/angular8-yandex-maps#34]
Добрый день! У меня тоже не обновляется состояние карты, но кейс немного другой. Без разницы есть ли кластеризация или нет. Ошибки в консоль не сыпятся, но визуальное обновление списка отметок происходит только когда я нажимаю что-либо на клавиатуре.

До актуальной версии (10.2.0) обновился.

upd: вызов любой функции компонента (в том числе через setInterval) тоже запускает перерисовку карты. Почему может без этого не отрабатывать?

_Originally posted by @tonghae in https://github.com/ddubrava/angular8-yandex-maps/issues/32#issuecomment-707524187_

**Comment by ddubrava** [comment]
@tonghae, добрый день, попробуйте detectChanges вызывать при изменении.
Пример: [create-geoobject-onclick](https://stackblitz.com/edit/create-geoobject-onclick)

**Comment by tonghae** [comment]
Благодарю! Сработало

**Comment by tonghae** [comment]
Аналогичная проблема при открытии диалогового окна (Material Dialog) по клику на точку на карте. Появляется окошко диалога, но не перерисовывается (т.е. его статический «скриншот» как бы), если нажать что-либо на клавиатуре, то запускается анимация появления окна и оно начинает реагировать на мышь.

**Comment by ddubrava** [comment]
Если несложно, то сделайте пример, пожалуйста. Сама библиотека никак не контактирует с change detection, поэтому перерисовку отключать не может. У вас onPush или default?

**Comment by tonghae** [comment]
Попытался форкнуть один из ваших примеров на том же сайте. К сожалению, я в этом увяз. Попробуйте по клику на маркер добавить открытие MatDialog, любого компонента.
С обеими вариантами onPush и default не отрабатывает.

**Comment by ddubrava** [comment]
@tonghae 
Выпустил версию `10.3.0`, обернул все `EventEmitter` в `NgZone`. Теперь `ChangeDetection` должен срабатывать

**Comment by ddubrava** [comment]
`npm install angular8-yandex-maps@10.3.1`. Обернул все `EventEmitters` в `NgZone.run()`, теперь `ChangeDetection` должен срабатывать

**Comment by tonghae** [comment]
Да, проблема ушла. Супер, спасибо!
