### ISSUE TITLE
setCenter dynamically

### ISSUE THREAD

**Issue by DmitriyLer** [ddubrava/angular8-yandex-maps#42]
How to set center dynamically?
I tried this - [https://stackblitz.com/edit/map-set-center-async?file=angular.json](https://stackblitz.com/edit/map-set-center-async?file=angular.json), but i got error - contacts.component.html:35 ERROR TypeError.

Help me please.)

update:

`<div class="project-map">
            <angular-yandex-map [center]="center" [zoom]="12">
                <angular-yandex-placemark *ngFor="let item of contactsMap"
                [geometry]="item?.geometry"
                [properties]="item?.properties"
                (load)="onLoad($event)"
                [options]="item?.options"></angular-yandex-placemark>
            </angular-yandex-map>
        </div>`

`import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { OtherService } from '../../shared/services/other.service';
import { ILoadEvent } from 'angular8-yandex-maps';

@Component({
  selector: 'app-contacts',
  templateUrl: './contacts.component.html',
  styleUrls: ['./contacts.component.scss']
})
export class ContactsComponent implements OnInit {

  contacts: any[];
  selected: any;
  contactsMap = [];
  center = [];

  constructor(private otherService: OtherService, private _changeDetectorRef: ChangeDetectorRef) { }

  ngOnInit(): void {
    this.center = [51.128207, 71.430411];
    this.otherService.getContacts()
      .then(res => {
        this.contacts = (res as any);
        this.selected = this.contacts[0];
        this.contactsMap.push(this.selected);
      })
  }

  getCoords(item) {
    if (item.lat && item.lng) {
      return [item.lat.toString(), item.lng.toString()];
    }
    else {
      return null;
    }
  }

  selectContact(item) {
    this.selected = item;
    this.contactsMap = [];
    this.contactsMap.push(this.selected);
    this._changeDetectorRef.detectChanges();
    this.setCenter(item.geometry);
  }

  getPlacemarksProperties(item) {
    return {
      hintContent: item.name,
      balloonContent: item.address
    }
  }

  public onLoad(event: ILoadEvent) {
    //this.map = event.instance;
  }

  public setCenter(coords: any[]): void {
    this.center = coords;
    //this.map.setCenter(coords);

  }

}`

**Comment by ddubrava** [comment]
Hey, I've updated the example to the latest version of the library so you can try again with the new code. Anyway, I can't help you without your code. So share your code, please

**Comment by DmitriyLer** [comment]
> Hey, I've updated the [example](https://stackblitz.com/edit/map-set-center-async) to the latest version of the library so you can try again with the new code. Anyway, I can't help you without your code. So share your code, please

How you changed example - i initially did, but i haven't result. I updated first message.

**Comment by DmitriyLer** [comment]
> Hey, I've updated the [example](https://stackblitz.com/edit/map-set-center-async) to the latest version of the library so you can try again with the new code. Anyway, I can't help you without your code. So share your code, please

Should i update to 10.4.0 ? I use 1.12.0

**Comment by ddubrava** [comment]
Yep. Versions follow Angular's version. E.g. for Angular 10, use ^10.0.0.
The example uses the latest library version

**Comment by DmitriyLer** [comment]
> Yep. Versions follow Angular's version. E.g. for Angular 10, use ^10.0.0.
> The example uses the latest library version

Thanks.) I will try it now.

**Comment by DmitriyLer** [comment]
It work, thank you. 
But i have some issues with angular ^10 and ya-map ^10.
I will create new topic now.
