### ISSUE TITLE
Ошибка при дестрое объекта карты

### ISSUE THREAD

**Issue by MaruBlare** [ddubrava/angular8-yandex-maps#43]
Здравствуйте! Ранее заводила проблему, связанную с ошибкой "Cannot read property 'geoObjects' of undefined" при использовании кластера (https://github.com/ddubrava/angular8-yandex-maps/issues/32). Сейчас сталкиваюсь в похожей проблемой, кейс подобный, но немного отличается. 
Есть несколько табов на странице - на каждом разный контент, при определенных условиях таб при инициализации меняется автоматически. На первом табе присутствует компонент карты и в случае, если карта еще не успела полностью отрисоваться, а таб переключается, в консоли падают ошибки Cannot read property 'geoObjects' of undefined и Cannot read property 'offsetWidth' of null, что крашит приложение. Также воспроизводится, если попытаться быстро переключить таб и вручную, есть вероятность, что карта все же не будет прогружена полностью. 
При дебаге кидает на строку кода на скрине (Cannot read property 'geoObjects' of undefined)
![image](https://user-images.githubusercontent.com/29026396/98448928-b304ec80-2140-11eb-8077-5ee4c473f957.png)
Cannot read property 'offsetWidth' of null генерится методом getSize

Пример - https://stackblitz.com/edit/ya-clusterer-tabs?file=src/app/map-container/map-container.component.ts

Начали ловить ошибку с версией библиотеки ^10.2.0.
Обновилась до версии ^10.4.0, дабы проверить сохраняется ли ошибка, но столкнулась со второй проблемой - не собирается проект с ошибками 'ymaps' refers to a UMD global, but the current file is a m
odule. Consider adding an import instead. (@types/yandex-maps установлен, верисия ^2.1.13). Подскажите, с чем это может быть связано?

**Comment by ddubrava** [comment]
Добрый день, исправил, спасибо!

`npm i angular8-yandex-maps`

**Comment by MaruBlare** [comment]
Вам спасибо! :)
