### ISSUE TITLE
Issues with angular ^10 and ya-maps ^10

### ISSUE THREAD

**Issue by DmitriyLer** [ddubrava/angular8-yandex-maps#44]
**Describe the bug**
After update from angular 9 to angular 10.2.0, and ya-map from 1.12.0 to 10.4.0 i have some execptions.

`
ERROR in node_modules/angular8-yandex-maps/lib/models/models.d.ts:45:19 - error TS2686: 'ymaps' refers to a UMD global, but the current file is a module. Consider adding an import instead.

45     ymaps: typeof ymaps;
                     ~~~~~
node_modules/angular8-yandex-maps/lib/models/models.d.ts:55:19 - error TS2686: 'ymaps' refers to a UMD global, but the current file is a module. Consider adding an import instead.

55     ymaps: typeof ymaps;
                     ~~~~~
node_modules/angular8-yandex-maps/lib/services/script/script.service.d.ts:19:45 - error TS2686: 'ymaps' refers to a UMD global, but the current file is a module. Consider adding an import instead.

19     initScript(): Observable<Event | typeof ymaps>;
`

**Package version**
`
@angular-devkit/architect       0.1002.0

@angular-devkit/build-angular   0.1002.0

@angular-devkit/core            10.2.0

@angular-devkit/schematics      10.2.0

@angular/cli                    10.2.0

@schematics/angular             10.2.0

@schematics/update              0.1002.0

rxjs                            6.5.5

typescript                      4.0.5

`

**Additional context**
`
{
  "name": "orda-satu-new", 

  "version": "0.0.0", 

  "scripts": { 

    "ng": "ng", 

    "start": "ng serve",

    "build": "ng build",

    "test": "ng test",

    "lint": "ng lint",

    "e2e": "ng e2e"

  },

  "private": true,

  "dependencies": {

    "@angular/animations": "~10.2.2",

    "@angular/common": "~10.2.2",

    "@angular/compiler": "~10.2.2",

    "@angular/core": "~10.2.2",

    "@angular/forms": "~10.2.2",

    "@angular/platform-browser": "~10.2.2",

    "@angular/platform-browser-dynamic": "~10.2.2",

    "@angular/router": "~10.2.2",

    "@fancyapps/fancybox": "^3.5.7",

    "@fortawesome/angular-fontawesome": "^0.7.0",

    "@fortawesome/fontawesome-svg-core": "^1.2.30",

    "@fortawesome/free-brands-svg-icons": "^5.14.0",

    "@fortawesome/free-solid-svg-icons": "^5.14.0",

    "@ng-bootstrap/ng-bootstrap": "^6.1.0",

    "@ngx-translate/core": "^12.1.2",

    "@ngx-translate/http-loader": "^4.0.0",

    "angular8-yandex-maps": "^10.4.0",

    "animate.css": "^3.7.2",

    "bootstrap": "^4.4.1",

    "ion-rangeslider": "^2.3.1",

    "jquery": "^3.5.1",

    "moment": "^2.25.1",

    "ng-bootstrap": "^1.6.3",

    "ng-image-slider": "^2.6.4",

    "ng-pdf-make": "^0.1.1",

    "ng2-ion-range-slider": "^2.0.0",

    "ngx-clipboard": "^13.0.1",

    "ngx-device-detector": "^1.4.5",

    "ngx-google-analytics": "^9.0.0",

    "ngx-image-zoom": "^0.6.0",

    "ngx-instabuy-utils": "0.0.5",

    "ngx-mask": "^9.0.2",

    "ngx-owl-carousel": "^2.0.7",

    "ngx-owl-carousel-o": "^3.0.0",

    "ngx-pipes": "^2.7.3",

    "ngx-sharebuttons": "^8.0.0",

    "owl-carousel": "^1.0.0",

    "owl.carousel": "^2.3.4",

    "rxjs": "~6.5.4",

    "script-loader": "^0.7.2",

    "tslib": "^2.0.0",

    "using-custom-elements": "^1.0.0",

    "zone.js": "~0.10.2"

  },

  "devDependencies": {

    "@angular-devkit/build-angular": "~0.1002.0",

    "@angular/cli": "^10.2.0",

    "@angular/compiler-cli": "~10.2.2",

    "@angular/language-service": "~10.2.2",

    "@types/jasmine": "~3.5.0",

    "@types/jasminewd2": "~2.0.3",

    "@types/jquery": "^3.3.38",

    "@types/node": "^12.11.1",

    "@types/yandex-maps": "^2.1.13",

    "codelyzer": "^5.1.2",

    "jasmine-core": "~3.5.0",

    "jasmine-spec-reporter": "~5.0.0",

    "karma": "~5.0.0",

    "karma-chrome-launcher": "~3.1.0",

    "karma-coverage-istanbul-reporter": "~3.0.2",

    "karma-jasmine": "~4.0.0",

    "karma-jasmine-html-reporter": "^1.5.0",

    "protractor": "~7.0.0",

    "ts-node": "~8.3.0",

    "tslint": "~6.1.0",

    "typescript": "~4.0.5"

  }
}
`

**Comment by DmitriyLer** [comment]
I added 
import * as ymaps from 'yandex-maps';
to files 
1) lib/models/models.d.ts
2) lib/services/script/script.service.d.ts
and now all work correctly

**Comment by MaruBlare** [comment]
I have the same problem with 10.4.0 version of  angular8-yandex-maps. 10.3.1 and previous versions work properly in this regard

**Comment by ddubrava** [comment]
You can downgrade to `10.3.1`.
Trying to fix the issue with 'yandex-maps' typings.
