### ISSUE TITLE
Замена @Component на @Directive, там где не используются html шаблоны

### ISSUE THREAD

**Issue by AwesomeObserver** [ddubrava/angular8-yandex-maps#46]
Feature request

Предлагаю заменить `@Component` на `@Directive`, потому что данные компоненты не имеют шаблонов (кроме `ya-map` и `ya-panorama`).
КМК это более правильное решение.
При этом решении, можно будет убрать не нужные html и scss файлы - станет чище

Пример: Google map в `@angular/components`
https://github.com/angular/components/blob/master/src/google-maps/map-bicycling-layer/map-bicycling-layer.ts#L21-L24

**Comment by ddubrava** [comment]
Привет, согласен, займусь.
Спасибо!
