### ISSUE TITLE
Multiroute

### ISSUE THREAD

**Issue by jorianp** [ddubrava/angular8-yandex-maps#55]
# ❓ Help Wanted

Can't use viaIndexes to hide viaPoints with option: viaPointVisible:false;

**Comment by ddubrava** [comment]
Hey!

1) `viaPointVisible` isn't documentated in Yandex.Maps API, use it at your own risk. The property should be passed in `options`
1.1) Yandex.Maps API - `multiRouter.MultiRoute(model[, options])`
1.2) Library - `[options]="{ viaPointVisible: false }"`

2) `viaIndexes` is the part of `multiRouter.MultiRouteModel`. The property should be passed in `model`
2.1) Yandex.Maps API - `multiRouter.MultiRoute(model[, options])`
2.2) Library - `[model]="{ params: { viaIndexes: [1, 2] } }"`

Please notice that `[referencePoints]="[0, 0]"` input is a shorthand for `[model]="{ referencePoints: [0, 0] }"` and it will override points from model.

```
const multiroute = new ymaps.multiRouter.MultiRoute(
  { ...this.model, referencePoints: this.referencePoints },
  this.options,
);
```

# Full example 

```
<ya-map [center]="[55.851952, 37.620739]">
  <ya-multiroute
    [referencePoints]="referencePoints"
    [model]="model"
    [options]="options"
  ></ya-multiroute>
</ya-map>
```

```
public referencePoints: number[][] = [
  [55.969297, 37.413372],
  [55.804902, 37.508129],
  [55.708876, 37.582287],
  [55.757693, 37.748455],
];

public model = {
  params: {
    viaIndexes: [1, 2],
  },
};

public options = {
  viaPointVisible: false,
};
```
