### ISSUE TITLE
Координаты клика

### ISSUE THREAD

**Issue by volik25** [ddubrava/angular8-yandex-maps#59]
# ❓ Help Wanted

Доброго времени суток! Перекопал кучу документации, но так и не понял, как мне получить координаты клика по карте?

Через (yaclick)="setPoint($event)" не нашел переменной с координатами или метода, их возвращающего.

Заранее благодарен!

**Comment by kirill-kot** [comment]
@volik25 делал через логику компонента вот так 

```
map.events.add("click", function (e) {
        map.geoObjects.removeAll();
        map.geoObjects.add(new ymaps.Placemark(e.get("coords"), {}, {}));
      });
```
