### ISSUE TITLE
При первой загрузке карты координаты перепутаны местами

### ISSUE THREAD

**Issue by Grenek** [ddubrava/angular8-yandex-maps#60]
# ❓ Help Wanted

## ✍️ Description

При первой загрузке приложения либо через жесткую перезагрузку со сбросом кэша метки на карте отображаются так 
![image](https://user-images.githubusercontent.com/6707565/104182046-e6a21280-5420-11eb-949b-43519bdcd4cc.png)
после обычной перезагрузки страницы метки отображаются корректно
![image](https://user-images.githubusercontent.com/6707565/104182149-0fc2a300-5421-11eb-95c8-e335c7bf4ecf.png)
Судя по всему почему-то путаются lat и lon

## 🌎 Environment

Angular CLI: 9.0.7
Node: 12.19.0
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      9.2.4
@angular/cli                      9.0.7
@angular/language-service         9.0.7
@angular/material                 9.2.4
@angular/router                   9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2

"angular8-yandex-maps": "^9.0.0",

**Comment by ddubrava** [comment]
Привет! Без примера, к сожалению, не помогу, т.к. не воспроизводится. В библиотеке входной объект `geometry` никак не модифицируется, он напрямую передается в API.

https://github.com/ddubrava/angular8-yandex-maps/blob/97b1ae3f0f1fc9f6f0d8d8499a1be992f2389549/projects/angular8-yandex-maps/src/lib/directives/ya-placemark/ya-placemark.directive.ts#L250-L254

P.S. Можно попробовать обновится до `^11.0.0` версии, возможно библиотека заработает на 9 версии ангуляра
