### ISSUE TITLE
Uncaught (in promise): ReferenceError: ymaps is not defined 

### ISSUE THREAD

**Issue by sa-va** [ddubrava/angular8-yandex-maps#64]

**Comment by sa-va** [comment]
возможно ли использование в lazy-loaded модуле с картой (для создания метки с собственным изображением)
```
myIconContentLayout = ymaps.templateLayoutFactory.createClass(
    '<div style="color: #FFFFFF; font-weight: bold;">$[properties.iconContent]</div>'
);
```
?   появляется ошибка "ReferenceError: ymaps is not defined"

angular8-yandex-maps v11.0.1

**Comment by sa-va** [comment]
и как в angular8-yandex-maps v11.0.1 установить bounds карты?
чем заменить код?
  public onLoad(event: ILoadEvent) {
    this.mapComponent = event.instance;
 }

**Comment by ddubrava** [comment]
> возможно ли использование в lazy-loaded модуле с картой (для создания метки с собственным изображением)
> 
> ```
> myIconContentLayout = ymaps.templateLayoutFactory.createClass(
>     '<div style="color: #FFFFFF; font-weight: bold;">$[properties.iconContent]</div>'
> );
> ```
> 
> ? появляется ошибка "ReferenceError: ymaps is not defined"
> 
> angular8-yandex-maps v11.0.1

```
<ya-map (ready)="onReady($event)">
```
```
public onReady(e: YaReadyEvent<ymaps.Map>): void {
  const { ymaps, target } = e;
  
  const CustomLayoutClass = ymaps.templateLayoutFactory.createClass(
    '<ul>' +
      '{% for name in properties.names %}' +
      '<li>{{ name }}</li>' +
      '{% endfor %}' +
      '</ul>',
  );
  
  const placemark = new ymaps.Placemark(
    [55.74, 37.58],
    { names: ['Logan', 'Sofia', 'Mason', 'Layla'] },
    { balloonContentLayout: CustomLayoutClass } as any,
  );
  
  target.geoObjects.add(placemark);
}
```

**Comment by ddubrava** [comment]
> и как в angular8-yandex-maps v11.0.1 установить bounds карты?
> чем заменить код?
> public onLoad(event: ILoadEvent) {
> this.mapComponent = event.instance;
> }

```
public onReady(e: YaReadyEvent<ymaps.Map>): void {
  const { target } = e;
  target.setBounds(...);
}
  ```
