### ISSUE TITLE
метка default#imageWithContent

### ISSUE THREAD

**Issue by sa-va** [ddubrava/angular8-yandex-maps#65]
Добрый день, в примере https://stackblitz.com/edit/custom-placemark я добавляю у метки обработчик события yaclick и все работает.
Но если у метки поменять iconLayout на 'default#imageWithContent', то событие не работает. Как можно это исправить?

**Comment by ddubrava** [comment]
Картинка смещается относительно реального положения метки, поэтому клик не считается. Надо добавить offset.

```
{
  // Необходимо указать данный тип макета.
  iconLayout: 'default#imageWithContent',
  // Своё изображение иконки метки.
  iconImageHref: 'images/ball.png',
  // Размеры метки.
  iconImageSize: [48, 48],
  // Смещение левого верхнего угла иконки относительно
  // её "ножки" (точки привязки).
  iconImageOffset: [-24, -24],
  // Смещение слоя с содержимым относительно слоя с картинкой.
  iconContentOffset: [15, 15],
  // Макет содержимого.
  iconContentLayout: MyIconContentLayout
});
```
