### ISSUE TITLE
Локальная ошибка запроса геокодера

### ISSUE THREAD

**Issue by kirill-kot** [ddubrava/angular8-yandex-maps#69]
# 🐞 Bug Report

## ✍️ Description

Геокодер не передаёт ключ при выполнении запроса.

## 🔬 Reproduction

Для примера возьмём вот этот же [стакблитз](https://stackblitz.com/edit/geocoder-v2-xkpezx?file=src%2Fapp%2Fapp.component.ts)

При вводе символа в поле ввода над картой отправляется такой запрос
![image](https://user-images.githubusercontent.com/48986387/110217948-035e4200-7ec8-11eb-84fb-3c0799051831.png)

При локальном, таком же запросе, апи-ключ куда-то теряется, хотя сама карта инициализируется и корректно работает, в том числе с прочими функциями.

![image](https://user-images.githubusercontent.com/48986387/110217970-2852b500-7ec8-11eb-846a-a254b4f03437.png)

подключение в модуле, компоненты которого используют апи карт
![image](https://user-images.githubusercontent.com/48986387/110218044-9303f080-7ec8-11eb-98f3-7f1d62d64888.png)

модуль в приложении подключен через ленивую загрузку
![image](https://user-images.githubusercontent.com/48986387/110218065-a9aa4780-7ec8-11eb-8cd4-236567b49ae5.png)

## 🌎 Environment
Angular CLI: 11.2.2
Node: 12.0.0
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

## Package Version
@angular-devkit/architect 0.1102.2
@angular-devkit/build-angular 0.1102.2
@angular-devkit/core 11.2.2
@angular-devkit/schematics 11.2.2
@angular/cli 11.2.2
@schematics/angular 11.2.2
@schematics/update 0.1102.2
rxjs 6.6.6
typescript 4.1.5

angular8-yandex-maps ^11.0.1

**Comment by ddubrava** [comment]
В примере, запущенном локально не воспроизводится. Библиотека не управляет запросами к геокодеру, они делаются со стороны API. Если при первоначальной загрузке API не теряется ключ, то проблема может быть в API, тогда надо максимально упрощать логику и дебажить. Либо же проблема с лейзи модулями

**Comment by kirill-kot** [comment]
> В примере, запущенном локально не воспроизводится. Библиотека не управляет запросами к геокодеру, они делаются со стороны API. Если при первоначальной загрузке API не теряется ключ, то проблема может быть в API, тогда надо максимально упрощать логику и дебажить. Либо же проблема с лейзи модулями

смотрел по примеру подключения для ленивых модулей отсюда https://github.com/ddubrava/angular8-yandex-maps/issues/21 пока проблема присутствует. Во встроенном поисковике такая же проблема - сервер не смог обработать запрос

**Comment by kirill-kot** [comment]
вопрос снимается. пересобрал с инициализацией карт в корневом компоненте как в примерах с ленивой загрузкой - баг не воспроизводится и работает корректно
