### ISSUE TITLE
Автоматическое открытие balloon при добавлении GeoObject

### ISSUE THREAD

**Issue by FrolovIgor** [ddubrava/angular8-yandex-maps#72]
Добрый день!

Angular CLI: 11.2.3
Node: 12.13.0
OS: darwin x64

Angular: 11.2.4

"angular8-yandex-maps": "11.0.1"

Я добавляю GeoObject на карту по щелчку, с помощью *ngFor

`        <ya-map [center]=[55.76,37.64]
                (yaclick)="yaMapClick($event)">
            <ya-geoobject *ngFor="let point of yaPoints" [feature]="point.feature"
                          [options]="point.options"></ya-geoobject>
        </ya-map>`
        
Для каждой точки я задаю содержимое balloon и мне нужно чтобы он сразу открывался

получилось навесить на каждый геообъект ya событие мыши
`        <ya-map [center]=[55.76,37.64]
                (yaclick)="yaMapClick($event)">
            <ya-geoobject *ngFor="let point of yaPoints" [feature]="point.feature"
                          (yamouseleave)="openBaloon($event)"
                          [options]="point.options"></ya-geoobject>
        </ya-map>`
тогда при наведении мыши на объект balloon открывается нормально
`    openBaloon(event: YaEvent) {
        event.target.balloon.open();
    }`
    
упорно не понимаю как вызвать метод balloon.open() автоматически при создании объекта

так же не получается просто открыть любой balloon с помощью
`const yaMap=event.ymaps.Balloon.prototype.open([55.76,37.64],'Example balloon');`
Ошибка
`ERROR TypeError: Cannot read property 'set' of undefined`

**Comment by ddubrava** [comment]
Привет, обновись, пожалуйста, до `11.0.2`
И вот пример: [create-geoobject-onclick-and-open-balloon](https://stackblitz.com/edit/create-geoobject-onclick-and-open-balloon?file=src/app/app.component.ts)

**Comment by FrolovIgor** [comment]
Спасибо большое! получилось
