### ISSUE TITLE
Error: getInternalNameOfClass() called on a non-ES5 class

### ISSUE THREAD

**Issue by sa-va** [ddubrava/angular8-yandex-maps#77]
Ошибка при сборке

версия  angular8-yandex-maps 11.0.2

[ERROR] Warning: Invalid constructor parameter decorator in E:/.../frontend/node_modules/angular8-yandex-maps/fesm2015/angular8-yandex-maps.js:
[ERROR]  () => [
[ERROR]     { type: NgZone }
[ERROR] ]
[ERROR] Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected YaGeoObjectComponent to have an inner class declaration
[ERROR]     at Esm5ReflectionHost.getInternalNameOfClass (E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\host\esm5_host.js:88:23)
[ERROR]     at DelegatingReflectionHost.getInternalNameOfClass (E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:89:34)
[ERROR]     at Object.extractDirectiveMetadata (E:\...\frontend\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:237:69)
[ERROR]     at ComponentDecoratorHandler.analyze (E:\...\frontend\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:143:47)
[ERROR]     at NgccTraitCompiler.TraitCompiler.analyzeTrait (E:\...\frontend\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:345:40)
[ERROR]     at analyze (E:\...\frontend\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:297:58)
[ERROR]     at _loop_1 (E:\...\frontend\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:319:21)
[ERROR]     at NgccTraitCompiler.TraitCompiler.analyzeClass (E:\...\frontend\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:325:35)
[ERROR]     at NgccTraitCompiler.analyzeFile (E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:47:26)
[ERROR]     at DecorationAnalyzer.analyzeProgram (E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:134:39)
[ERROR]     at ClusterMaster.onWorkerMessage (E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:194:27)
[ERROR]     at E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:54:95
[ERROR]     at ClusterMaster.<anonymous> (E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:292:57)
[ERROR]     at step (E:\...\frontend\node_modules\tslib\tslib.js:141:27)
[ERROR]     at Object.next (E:\...\frontend\node_modules\tslib\tslib.js:122:57)
[ERROR]     at E:\...\frontend\node_modules\tslib\tslib.js:115:75
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at Object.__awaiter (E:\...\frontend\node_modules\tslib\tslib.js:111:16)
[ERROR]     at EventEmitter.<anonymous> (E:\...\frontend\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:286:32)
[ERROR]     at EventEmitter.emit (events.js:315:20)
[ERROR] An unhandled exception occurred: NGCC failed.
[ERROR] See "C:\...\angular-errors.log" for further details.
[ERROR] npm ERR! file C:\Windows\system32\cmd.exe
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn
[ERROR] npm ERR! emias@0.0.1 build-prod: `node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod`
[ERROR] npm ERR! spawn ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the emias@0.0.1 build-prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

(если в package.json дописать "postinstall": "ngcc", то ошибка пропадает)

**Comment by ddubrava** [comment]
Привет, у меня не получается воспроизвести. Попробуй поменять `compilerOptions.target` в `tsconfig.json` на `es2015`. Или если использовать `es5`, то вместе с `"postinstall": "ngcc"`.

**Comment by sa-va** [comment]
спасибо, с es2015 компилируется
