### ISSUE TITLE
Версия 11.0.2 не работает с Firefox 45

### ISSUE THREAD

**Issue by sa-va** [ddubrava/angular8-yandex-maps#78]
Ошибка     SyntaxError: missing : after property id
Возможно ли это исправить?

версия 1.15-2 работают в ff45, но там не меняется iconColor по условию

**Comment by ddubrava** [comment]
Привет, с ff45 тяжело помочь, очень старая версия.
Можно попробовать `npm i angular8-yandex-maps@6.0.0`

**Comment by sa-va** [comment]
спасибо. 
а можно каким-то методом перезагрузить карту?
