### ISSUE TITLE
Как задать параметеры objectManager'у?

### ISSUE THREAD

**Issue by siamskoi** [ddubrava/angular8-yandex-maps#95]
Не нашел в документации и в примерах, как можно задать параметры для objectManager'а, например geoObjectOpenBalloonOnClick. И как через него в коде можно добавить объекты.

**Comment by ddubrava** [comment]
https://stackblitz.com/edit/geoobject-manager?file=src/app/app.component.ts

Привет, отдельного компонента под `objectManager` нет, поэтому надо использовать глобальный объект. Его можно получить после загрузки карты, используя `(ready)` ивент у компонента (в данном случае карты). В пример добавил комментарии. Постараюсь добавить в документацию примеры использования `(ready)`.
